### ISSUE TITLE
Backend: User Route

### ISSUE THREAD

**Issue by Tbos92** [TheOGAltruist/the-stadium#5]
For admins to view all users, modify them in the backend, promote/demote from Admin, password reset, view orders, etc.

**Comment by TheOGAltruist** [comment]
Added route to get all users.

**Comment by TheOGAltruist** [comment]
All users route is a protected route. Route is for admins only since in a ecommerce web app, there is no need for any other user to fetch all users.

**Comment by TheOGAltruist** [comment]
Added a route for a single user. This is also an admin-only route.

**Comment by TheOGAltruist** [comment]
Added a route for modifying a user. This is also an admin-only route.
